/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an OpenSpec change.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - Context file paths (varies by schema - could be proposal/specs/design/tasks or spec/tests/implementation/docs)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using openspec-continue-change
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

4. **Read context files**

   Read the files listed in \`contextFiles\` from the apply instructions output.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks
   - Other schemas: follow the contextFiles from CLI output

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

6. **Environment Setup (first task only)**

   Before implementing the first task, check if the project has Docker and structured logging set up. If not, set them up:

   **Docker Setup** (if no \`Dockerfile\` or \`docker-compose.yml\` exists):
   - Analyze the project structure to identify services, databases, and dependencies
   - Generate a multi-stage \`Dockerfile\` with dev/build/production targets
   - Generate \`docker-compose.yml\` with appropriate services, health checks, and volume mounts
   - Run \`docker compose up -d --build --wait\` and verify all containers are healthy
   - Run a smoke test: hit health endpoints, verify structured JSON logs are visible

   **Structured Logging Setup** (if the codebase lacks JSON structured logging):
   - Instrument the codebase with the appropriate logging library for the stack:
     - **Node.js**: pino + AsyncLocalStorage for trace_id propagation
     - **Python**: structlog + contextvars for trace_id propagation
     - **Go**: zerolog + context.Context for trace_id propagation
   - Every log line must include: \`timestamp\`, \`level\`, \`service\`, \`message\`, \`trace_id\`
   - Error-level logs must also include: \`error_category\` (one of: timeout, connection, validation, logic, auth, rate_limit, unknown), \`error_detail\`, \`stack_trace\` (max 10 lines)
   - Set Docker environment variables: \`LOG_FORMAT=json\`, \`LOG_LEVEL=info\`, \`SERVICE_NAME=<name>\`
   - Never log: passwords, tokens, API keys, session IDs, full request/response bodies, SQL queries with parameters

   **Exit criteria for setup:**
   - All containers show "healthy" in \`docker compose ps\`
   - Health endpoints respond with 200
   - Structured JSON logs visible in \`docker compose logs\`

   Skip this step if Docker and structured logging already exist.

7. **Implement tasks with TDD and verification (loop until done or blocked)**

   For each pending task, follow this loop:

   **Step A: TDD Cycle (Red-Green-Refactor)**

   1. Read the task and its verification profile (the \`**Verification:**\` line)
   2. **RED**: Write a failing test that captures the expected behavior. One behavior per test. Clear name describing what it tests.
   3. **Verify RED**: Run the test. It MUST fail. If it passes, the test is wrong — rewrite it. The failure reason should be "feature missing", not a typo or import error.
   4. **GREEN**: Write the minimal code to make the test pass. Just enough — no extra features, no premature optimization.
   5. **Verify GREEN**: Run the test. It MUST pass. All other tests must still pass too.
   6. **REFACTOR**: Clean up and refactor while tests are green — remove duplication, improve names, extract helpers. Keep all tests passing.

   Never skip the red step. A test written after implementation proves nothing — you never saw it catch the bug.

   **Step B: Deploy to Docker**

   Deploy changes to running containers:
   - Preferred: \`docker compose watch\` (hot reload if supported)
   - Fallback: \`docker compose up --build -d\`
   - Wait for containers to be healthy before proceeding

   **Step C: Verification Gate**

   Run the signals specified by the task's verification profile, in cost order. Stop on critical failure — no point running expensive signals if cheap ones fail.

   | Signal | Time | Blocking | What it checks |
   |---|---|---|---|
   | Static analysis (lint + typecheck) | ~5s | Yes | Code quality, type safety |
   | Property-based tests | ~30s | Yes | Spec compliance |
   | Mutation testing | ~2min | No (warning) | Test quality — are tests catching real bugs? |
   | Contract validation | ~10s | Yes | FE/BE API shape agreement |
   | DST simulation | ~3min | No (warning) | Resilience under fault injection |
   | E2E tests | ~1-3min | Yes | Full user flow verification |

   Not all signals apply to every task — only run the signals listed in the task's verification profile.

   **Step D: Auto-Debug on Failure (using structured logs)**

   If any blocking signal fails, do NOT retry blindly. Follow systematic debugging:

   1. **Read structured logs** from Docker containers:
      \`\`\`bash
      docker compose logs --no-log-prefix --tail 100 <service> | jq -R 'fromjson? // empty | select(.level == "error")'
      \`\`\`
   2. **Categorize the error** by \`error_category\` field:
      - \`timeout\` → Add timeout config, circuit breaker
      - \`connection\` → Verify service networking, add retry logic
      - \`validation\` → Fix input/output schema mismatch
      - \`logic\` → Fix business rule implementation
      - \`auth\` → Fix token handling, permissions
      - \`rate_limit\` → Add backoff, queue, caching
      - \`unknown\` → Investigate deeper, add proper error handling
   3. **Trace the root cause**: Use \`trace_id\` to follow the request across services:
      \`\`\`bash
      docker compose logs --no-log-prefix | jq -R 'fromjson? // empty | select(.trace_id == "<id>")' | jq -s 'sort_by(.timestamp)'
      \`\`\`
   4. **Form a single hypothesis**: State clearly "I think X is the root cause because Y"
   5. **Test minimal fix**: Make the smallest possible change, one variable at a time
   6. **Re-run the gate**: Only the failing signals need to re-run

   **Loop Guard — escalate instead of looping forever:**
   - Same error 2 consecutive attempts → **STUCK** — report to user with full diagnosis
   - 5 total attempts on same task → **EXHAUSTED** — report with complete attempt history
   - Container won't start → **INFRASTRUCTURE** — escalate immediately
   - Each fix reveals new problem elsewhere → Likely architectural issue — **STOP and discuss with user**

   **Step E: Proceed**

   When all gate signals pass:
   - Mark task complete in tasks file: \`- [ ]\` → \`- [x]\`
   - Commit the verified code
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Loop guard triggered (STUCK/EXHAUSTED/INFRASTRUCTURE) → report and wait
   - User interrupts

8. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Ready to archive this change.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement tasks from an OpenSpec change (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Implement tasks from an OpenSpec change.

**Input**: Optionally specify a change name (e.g., \`/opsx:apply add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - Context file paths (varies by schema)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using \`/opsx:continue\`
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

4. **Read context files**

   Read the files listed in \`contextFiles\` from the apply instructions output.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, tasks
   - Other schemas: follow the contextFiles from CLI output

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

6. **Environment Setup (first task only)**

   Before implementing the first task, check if the project has Docker and structured logging set up. If not, set them up:

   **Docker Setup** (if no \`Dockerfile\` or \`docker-compose.yml\` exists):
   - Analyze the project structure to identify services, databases, and dependencies
   - Generate a multi-stage \`Dockerfile\` with dev/build/production targets
   - Generate \`docker-compose.yml\` with appropriate services, health checks, and volume mounts
   - Run \`docker compose up -d --build --wait\` and verify all containers are healthy
   - Run a smoke test: hit health endpoints, verify structured JSON logs are visible

   **Structured Logging Setup** (if the codebase lacks JSON structured logging):
   - Instrument the codebase with the appropriate logging library for the stack:
     - **Node.js**: pino + AsyncLocalStorage for trace_id propagation
     - **Python**: structlog + contextvars for trace_id propagation
     - **Go**: zerolog + context.Context for trace_id propagation
   - Every log line must include: \`timestamp\`, \`level\`, \`service\`, \`message\`, \`trace_id\`
   - Error-level logs must also include: \`error_category\` (one of: timeout, connection, validation, logic, auth, rate_limit, unknown), \`error_detail\`, \`stack_trace\` (max 10 lines)
   - Set Docker environment variables: \`LOG_FORMAT=json\`, \`LOG_LEVEL=info\`, \`SERVICE_NAME=<name>\`
   - Never log: passwords, tokens, API keys, session IDs, full request/response bodies, SQL queries with parameters

   **Exit criteria for setup:**
   - All containers show "healthy" in \`docker compose ps\`
   - Health endpoints respond with 200
   - Structured JSON logs visible in \`docker compose logs\`

   Skip this step if Docker and structured logging already exist.

7. **Implement tasks with TDD and verification (loop until done or blocked)**

   For each pending task, follow this loop:

   **Step A: TDD Cycle (Red-Green-Refactor)**

   1. Read the task and its verification profile (the \`**Verification:**\` line)
   2. **RED**: Write a failing test that captures the expected behavior. One behavior per test. Clear name describing what it tests.
   3. **Verify RED**: Run the test. It MUST fail. If it passes, the test is wrong — rewrite it. The failure reason should be "feature missing", not a typo or import error.
   4. **GREEN**: Write the minimal code to make the test pass. Just enough — no extra features, no premature optimization.
   5. **Verify GREEN**: Run the test. It MUST pass. All other tests must still pass too.
   6. **REFACTOR**: Clean up and refactor while tests are green — remove duplication, improve names, extract helpers. Keep all tests passing.

   Never skip the red step. A test written after implementation proves nothing — you never saw it catch the bug.

   **Step B: Deploy to Docker**

   Deploy changes to running containers:
   - Preferred: \`docker compose watch\` (hot reload if supported)
   - Fallback: \`docker compose up --build -d\`
   - Wait for containers to be healthy before proceeding

   **Step C: Verification Gate**

   Run the signals specified by the task's verification profile, in cost order. Stop on critical failure — no point running expensive signals if cheap ones fail.

   | Signal | Time | Blocking | What it checks |
   |---|---|---|---|
   | Static analysis (lint + typecheck) | ~5s | Yes | Code quality, type safety |
   | Property-based tests | ~30s | Yes | Spec compliance |
   | Mutation testing | ~2min | No (warning) | Test quality — are tests catching real bugs? |
   | Contract validation | ~10s | Yes | FE/BE API shape agreement |
   | DST simulation | ~3min | No (warning) | Resilience under fault injection |
   | E2E tests | ~1-3min | Yes | Full user flow verification |

   Not all signals apply to every task — only run the signals listed in the task's verification profile.

   **Step D: Auto-Debug on Failure (using structured logs)**

   If any blocking signal fails, do NOT retry blindly. Follow systematic debugging:

   1. **Read structured logs** from Docker containers:
      \`\`\`bash
      docker compose logs --no-log-prefix --tail 100 <service> | jq -R 'fromjson? // empty | select(.level == "error")'
      \`\`\`
   2. **Categorize the error** by \`error_category\` field:
      - \`timeout\` → Add timeout config, circuit breaker
      - \`connection\` → Verify service networking, add retry logic
      - \`validation\` → Fix input/output schema mismatch
      - \`logic\` → Fix business rule implementation
      - \`auth\` → Fix token handling, permissions
      - \`rate_limit\` → Add backoff, queue, caching
      - \`unknown\` → Investigate deeper, add proper error handling
   3. **Trace the root cause**: Use \`trace_id\` to follow the request across services:
      \`\`\`bash
      docker compose logs --no-log-prefix | jq -R 'fromjson? // empty | select(.trace_id == "<id>")' | jq -s 'sort_by(.timestamp)'
      \`\`\`
   4. **Form a single hypothesis**: State clearly "I think X is the root cause because Y"
   5. **Test minimal fix**: Make the smallest possible change, one variable at a time
   6. **Re-run the gate**: Only the failing signals need to re-run

   **Loop Guard — escalate instead of looping forever:**
   - Same error 2 consecutive attempts → **STUCK** — report to user with full diagnosis
   - 5 total attempts on same task → **EXHAUSTED** — report with complete attempt history
   - Container won't start → **INFRASTRUCTURE** — escalate immediately
   - Each fix reveals new problem elsewhere → Likely architectural issue — **STOP and discuss with user**

   **Step E: Proceed**

   When all gate signals pass:
   - Mark task complete in tasks file: \`- [ ]\` → \`- [x]\`
   - Commit the verified code
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Loop guard triggered (STUCK/EXHAUSTED/INFRASTRUCTURE) → report and wait
   - User interrupts

8. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! You can archive this change with \`/opsx:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`
  };
}
