/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description: 'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. **Get the change directory and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If tasks.md exists in contextFiles, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`openspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If design.md exists in contextFiles:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Unified Verification Report**:

   \`\`\`json
   {
     "verification_report": {
       "spec_compliance": {
         "completeness": "PASS|FAIL",
         "correctness": "PASS|FAIL",
         "coherence": "PASS|FAIL",
         "issues": []
       },
       "dst_simulation": {
         "scenarios_passed": 0,
         "scenarios_failed": 0,
         "critical_findings": [],
         "skipped": false,
         "skip_reason": null
       },
       "e2e": {
         "figma_compliance": { "passed": 0, "failed": 0 },
         "business_workflows": { "passed": 0, "failed": 0 },
         "smoke": { "passed": 0, "failed": 0 },
         "skipped": false,
         "skip_reason": null
       },
       "gate": {
         "lint": "PASS|FAIL|SKIP",
         "typecheck": "PASS|FAIL|SKIP",
         "tests": "PASS|FAIL|SKIP",
         "exit_codes": {}
       },
       "code_review": {
         "critical": 0,
         "important": 0,
         "minor": 0,
         "assessment": "ready|fix_issues|escalate",
         "findings": []
       },
       "overall": "PASS|FAIL"
     }
   }
   \`\`\`

   Also display a human-readable summary:

   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Phase | Status |
   |---|---|
   | Spec Compliance | PASS/FAIL (X/Y tasks, N/M reqs) |
   | DST Simulation | PASS/FAIL/SKIP (N scenarios) |
   | E2E Tests | PASS/FAIL/SKIP (N tests) |
   | Pre-complete Gate | PASS/FAIL (lint, typecheck, tests) |
   | Code Review | Ready/Fix Issues/Escalate (N findings) |
   | **Overall** | **PASS/FAIL** |
   \`\`\`

9. **DST Simulation (Fault Injection)**

   If Docker containers are running, run fault injection to find resilience gaps. Use Toxiproxy as a sidecar proxy.

   **Setup** (if not already configured):
   - Generate a DST overlay \`docker-compose.dst.yml\` with Toxiproxy sidecar (ports 8474, 8001, 5433, 8002) and WireMock (port 8080)
   - Rewire service URLs through Toxiproxy proxies
   - Run: \`docker compose -f docker-compose.yml -f docker-compose.dst.yml up -d\`

   **Run 6 fault scenarios** (for each: inject fault → test → capture → remove fault → verify recovery):

   | Scenario | Fault | What it tests |
   |---|---|---|
   | Network latency (FE ↔ BE) | 2000ms latency via Toxiproxy | Timeout handling, loading states |
   | Connection reset (FE ↔ BE) | Reset peer via Toxiproxy | Retry logic, error messages |
   | Database timeout (BE ↔ DB) | 5000ms timeout via Toxiproxy | Query timeout handling, connection pool |
   | External API failure (BE ↔ 3rd party) | Connection reset via WireMock | Fallback behavior, circuit breakers |
   | Service crash & recovery | \`docker compose stop/start backend\` | Reconnection, state recovery |
   | Bandwidth restriction | 10 rate limit via Toxiproxy | Graceful degradation |

   **Categorize findings:**
   - \`startup_error\` — Boot failure
   - \`integration_error\` — Service communication failure
   - \`resilience\` — Recovery failure after fault removal
   - \`timeout_handling\` — Missing or inadequate timeout handling
   - \`error_handling\` — Unhandled exceptions under fault
   - \`state_management\` — Corrupted state after fault
   - \`recovery\` — Failed to recover after fault removed

   Skip this step if Docker is not set up. Note "DST skipped: no Docker environment" in the report.

10. **E2E Verification (Playwright)**

    Run the full Playwright e2e suite. If Playwright is not set up, set it up first:
    - Install: \`npm init playwright@latest\`
    - Create \`playwright.config.ts\` with three projects:

    **Project 1: Figma-Compliance** (if Figma designs exist)
    - Design token assertions: compare computed CSS against design tokens
    - Visual regression: screenshot comparison with \`maxDiffPixelRatio: 0.01\`
    - Structural matching: verify DOM structure matches component hierarchy

    **Project 2: Business-Workflows**
    - User journey tests based on the spec's scenarios
    - Each \`#### Scenario:\` from the delta specs becomes an e2e test
    - Test primary flows: browsing, forms, data persistence, error states

    **Project 3: Smoke** (always runs)
    - App loads successfully
    - API health endpoint responds
    - Primary content renders

    Run: \`npx playwright test\`

    Skip this step if the project has no frontend. Note "E2E skipped: no frontend detected" in the report.

11. **Pre-complete Gate**

    **Iron law: NO COMPLETION CLAIMS WITHOUT FRESH VERIFICATION EVIDENCE**

    Before generating the final report:
    1. **Identify** what commands prove the implementation is correct (lint, typecheck, test suite)
    2. **Run** each command fresh — no cached results, no previous runs
    3. **Read** full output — check exit code, count failures, read error messages
    4. **Verify** the output confirms the claim
    5. **Only then** make completion claims in the report

    **Red flags — STOP if you catch yourself:**
    - Using "should", "probably", "seems to" instead of concrete evidence
    - Expressing satisfaction ("Great!", "Perfect!", "Done!") before running verification
    - About to generate the report without running commands first
    - Trusting cached or previous test results instead of running fresh

    | Claim | Requires | NOT Sufficient |
    |---|---|---|
    | Tests pass | Test command output: 0 failures, exit code 0 | Previous run, "should pass" |
    | Linter clean | Linter output: 0 errors, 0 warnings | Partial check, typecheck only |
    | Build succeeds | Build command: exit code 0 | Linter passing |
    | Bug fixed | Reproduce original symptom: now passes | "Code changed, assumed fixed" |

12. **Code Review**

    Review all code changes in the change:

    1. **Gather the diff**: All commits since the change began
       \`\`\`bash
       git diff <base-commit>..HEAD
       \`\`\`
    2. **Review against the spec**: Check each requirement, scenario, and design decision against the implementation
    3. **Check for common issues:**
       - Missed requirements from the spec
       - Security vulnerabilities (OWASP top 10: injection, XSS, auth bypass, etc.)
       - Test gaps — untested edge cases, missing error path tests
       - Code quality — duplication, unclear naming, overly complex logic
       - API contract mismatches between frontend and backend
    4. **Categorize findings:**
       - **CRITICAL**: Must fix before archiving (security issues, missed requirements, broken functionality)
       - **IMPORTANT**: Should fix (test gaps, significant code quality issues)
       - **MINOR**: Nice to fix (style, naming, minor improvements)
    5. **Assessment:**
       - "Ready to archive" — no critical issues
       - "Fix issues then archive" — critical issues found with specific recommendations
       - "Escalate to human" — architectural concerns or ambiguous requirements needing human judgment

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: `Verify that an implementation matches the change artifacts (specs, tasks, design).

**Input**: Optionally specify a change name after \`/opsx:verify\` (e.g., \`/opsx:verify add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - Which artifacts exist for this change

3. **Get the change directory and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and context files. Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If tasks.md exists in contextFiles, read it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`openspec/changes/<name>/specs/\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If design.md exists in contextFiles:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Unified Verification Report**:

   \`\`\`json
   {
     "verification_report": {
       "spec_compliance": {
         "completeness": "PASS|FAIL",
         "correctness": "PASS|FAIL",
         "coherence": "PASS|FAIL",
         "issues": []
       },
       "dst_simulation": {
         "scenarios_passed": 0,
         "scenarios_failed": 0,
         "critical_findings": [],
         "skipped": false,
         "skip_reason": null
       },
       "e2e": {
         "figma_compliance": { "passed": 0, "failed": 0 },
         "business_workflows": { "passed": 0, "failed": 0 },
         "smoke": { "passed": 0, "failed": 0 },
         "skipped": false,
         "skip_reason": null
       },
       "gate": {
         "lint": "PASS|FAIL|SKIP",
         "typecheck": "PASS|FAIL|SKIP",
         "tests": "PASS|FAIL|SKIP",
         "exit_codes": {}
       },
       "code_review": {
         "critical": 0,
         "important": 0,
         "minor": 0,
         "assessment": "ready|fix_issues|escalate",
         "findings": []
       },
       "overall": "PASS|FAIL"
     }
   }
   \`\`\`

   Also display a human-readable summary:

   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Phase | Status |
   |---|---|
   | Spec Compliance | PASS/FAIL (X/Y tasks, N/M reqs) |
   | DST Simulation | PASS/FAIL/SKIP (N scenarios) |
   | E2E Tests | PASS/FAIL/SKIP (N tests) |
   | Pre-complete Gate | PASS/FAIL (lint, typecheck, tests) |
   | Code Review | Ready/Fix Issues/Escalate (N findings) |
   | **Overall** | **PASS/FAIL** |
   \`\`\`

9. **DST Simulation (Fault Injection)**

   If Docker containers are running, run fault injection to find resilience gaps. Use Toxiproxy as a sidecar proxy.

   **Setup** (if not already configured):
   - Generate a DST overlay \`docker-compose.dst.yml\` with Toxiproxy sidecar (ports 8474, 8001, 5433, 8002) and WireMock (port 8080)
   - Rewire service URLs through Toxiproxy proxies
   - Run: \`docker compose -f docker-compose.yml -f docker-compose.dst.yml up -d\`

   **Run 6 fault scenarios** (for each: inject fault → test → capture → remove fault → verify recovery):

   | Scenario | Fault | What it tests |
   |---|---|---|
   | Network latency (FE ↔ BE) | 2000ms latency via Toxiproxy | Timeout handling, loading states |
   | Connection reset (FE ↔ BE) | Reset peer via Toxiproxy | Retry logic, error messages |
   | Database timeout (BE ↔ DB) | 5000ms timeout via Toxiproxy | Query timeout handling, connection pool |
   | External API failure (BE ↔ 3rd party) | Connection reset via WireMock | Fallback behavior, circuit breakers |
   | Service crash & recovery | \`docker compose stop/start backend\` | Reconnection, state recovery |
   | Bandwidth restriction | 10 rate limit via Toxiproxy | Graceful degradation |

   **Categorize findings:**
   - \`startup_error\` — Boot failure
   - \`integration_error\` — Service communication failure
   - \`resilience\` — Recovery failure after fault removal
   - \`timeout_handling\` — Missing or inadequate timeout handling
   - \`error_handling\` — Unhandled exceptions under fault
   - \`state_management\` — Corrupted state after fault
   - \`recovery\` — Failed to recover after fault removed

   Skip this step if Docker is not set up. Note "DST skipped: no Docker environment" in the report.

10. **E2E Verification (Playwright)**

    Run the full Playwright e2e suite. If Playwright is not set up, set it up first:
    - Install: \`npm init playwright@latest\`
    - Create \`playwright.config.ts\` with three projects:

    **Project 1: Figma-Compliance** (if Figma designs exist)
    - Design token assertions: compare computed CSS against design tokens
    - Visual regression: screenshot comparison with \`maxDiffPixelRatio: 0.01\`
    - Structural matching: verify DOM structure matches component hierarchy

    **Project 2: Business-Workflows**
    - User journey tests based on the spec's scenarios
    - Each \`#### Scenario:\` from the delta specs becomes an e2e test
    - Test primary flows: browsing, forms, data persistence, error states

    **Project 3: Smoke** (always runs)
    - App loads successfully
    - API health endpoint responds
    - Primary content renders

    Run: \`npx playwright test\`

    Skip this step if the project has no frontend. Note "E2E skipped: no frontend detected" in the report.

11. **Pre-complete Gate**

    **Iron law: NO COMPLETION CLAIMS WITHOUT FRESH VERIFICATION EVIDENCE**

    Before generating the final report:
    1. **Identify** what commands prove the implementation is correct (lint, typecheck, test suite)
    2. **Run** each command fresh — no cached results, no previous runs
    3. **Read** full output — check exit code, count failures, read error messages
    4. **Verify** the output confirms the claim
    5. **Only then** make completion claims in the report

    **Red flags — STOP if you catch yourself:**
    - Using "should", "probably", "seems to" instead of concrete evidence
    - Expressing satisfaction ("Great!", "Perfect!", "Done!") before running verification
    - About to generate the report without running commands first
    - Trusting cached or previous test results instead of running fresh

    | Claim | Requires | NOT Sufficient |
    |---|---|---|
    | Tests pass | Test command output: 0 failures, exit code 0 | Previous run, "should pass" |
    | Linter clean | Linter output: 0 errors, 0 warnings | Partial check, typecheck only |
    | Build succeeds | Build command: exit code 0 | Linter passing |
    | Bug fixed | Reproduce original symptom: now passes | "Code changed, assumed fixed" |

12. **Code Review**

    Review all code changes in the change:

    1. **Gather the diff**: All commits since the change began
       \`\`\`bash
       git diff <base-commit>..HEAD
       \`\`\`
    2. **Review against the spec**: Check each requirement, scenario, and design decision against the implementation
    3. **Check for common issues:**
       - Missed requirements from the spec
       - Security vulnerabilities (OWASP top 10: injection, XSS, auth bypass, etc.)
       - Test gaps — untested edge cases, missing error path tests
       - Code quality — duplication, unclear naming, overly complex logic
       - API contract mismatches between frontend and backend
    4. **Categorize findings:**
       - **CRITICAL**: Must fix before archiving (security issues, missed requirements, broken functionality)
       - **IMPORTANT**: Should fix (test gaps, significant code quality issues)
       - **MINOR**: Nice to fix (style, naming, minor improvements)
    5. **Assessment:**
       - "Ready to archive" — no critical issues
       - "Fix issues then archive" — critical issues found with specific recommendations
       - "Escalate to human" — architectural concerns or ambiguous requirements needing human judgment

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`
  };
}
